package com.linkage.core.constants;

import java.util.ArrayList;
import java.util.List;

public abstract class HspKeywords {
    private HspKeywords() {
    }

    public static List<String> hspKeys() {
        ArrayList<String> hspKeywords = new ArrayList<>();

        hspKeywords.add("vascular surgery");
        hspKeywords.add("vascular medicine");
        hspKeywords.add("urology");
        hspKeywords.add("sports medicine");
        hspKeywords.add("radiology");
        hspKeywords.add("radiation oncology");
        hspKeywords.add("pulmonology");
        hspKeywords.add("public health");
        hspKeywords.add("psychiatry");
        hspKeywords.add("plastic, reconstructive and aesthetic surgery");
        hspKeywords.add("physical medicine and rehabilitation");
        hspKeywords.add("pathology");
        hspKeywords.add("paediatric");
        hspKeywords.add("paediatric surgery");
        hspKeywords.add("paediatric rheumatology");
        hspKeywords.add("paediatric respiratory medicine");
        hspKeywords.add("paediatric nephrology");
        hspKeywords.add("paediatric infectious diseases");
        hspKeywords.add("paediatric haematology and oncology");
        hspKeywords.add("paediatric gastroenterology, hepatology and nutrition");
        hspKeywords.add("paediatric endocrinology and diabetes");
        hspKeywords.add("paediatric cardiology");
        hspKeywords.add("paediatric allergology");
        hspKeywords.add("otorhinolaryngology");
        hspKeywords.add("orthopaedics");
        hspKeywords.add("orthodontics");
        hspKeywords.add("oral and maxillofacial surgery");
        hspKeywords.add("ophthalmology");
        hspKeywords.add("occupational medicine");
        hspKeywords.add("obstetrics and gynaecology");
        hspKeywords.add("nuclear medicine");
        hspKeywords.add("neurosurgery");
        hspKeywords.add("neuroradiology");
        hspKeywords.add("neurology");
        hspKeywords.add("nephrology");
        hspKeywords.add("neonatology");
        hspKeywords.add("interventional radiology");
        hspKeywords.add("internal medicine");
        hspKeywords.add("intensive care medicine");
        hspKeywords.add("infectious disease");
        hspKeywords.add("hospice and palliative medicine");
        hspKeywords.add("health informatics");
        hspKeywords.add("geriatrics");
        hspKeywords.add("general surgery");
        hspKeywords.add("general practice");
        hspKeywords.add("gastroenterology");
        hspKeywords.add("endocrinology");
        hspKeywords.add("emergency medicine");
        hspKeywords.add("dermatology-venereology");
        hspKeywords.add("colon and rectal surgery");
        hspKeywords.add("clinical neurophysiology");
        hspKeywords.add("child and adolescent psychiatry and psychotherapy");
        hspKeywords.add("cardiothoracic surgery");
        hspKeywords.add("cardiology");
        hspKeywords.add("anaesthesiology");
        hspKeywords.add("allergy and immunology");
        hspKeywords.add("aerospace medicine");
        hspKeywords.add("adolescent medicine");
        hspKeywords.add("hospital");
        hspKeywords.add("hospitals");
        hspKeywords.add("clinic");
        hspKeywords.add("clinics");
        hspKeywords.add("laboratory");
        hspKeywords.add("laboratories");
        hspKeywords.add("medical");
        hspKeywords.add("medicals");
        hspKeywords.add("pharmacy");
        hspKeywords.add("nursing home");
        hspKeywords.add("diagnostic");
        hspKeywords.add("dispensary");
        hspKeywords.add("trauma centre");
        hspKeywords.add("hospitals");
        hspKeywords.add("diagnostics");
        hspKeywords.add("laboratories");
        hspKeywords.add("health");
        hspKeywords.add("labs");
        hspKeywords.add("lab");
        hspKeywords.add("cancer centre");
        hspKeywords.add("medicos");
        hspKeywords.add("eye care");
        hspKeywords.add("medicare centre");
        hspKeywords.add("medicare center");
        hspKeywords.add("eyecare centre");
        hspKeywords.add("eyecare center");
        hspKeywords.add("medico");
        hspKeywords.add("adrenals");
        hspKeywords.add("appendix");
        hspKeywords.add("bladder");
        hspKeywords.add("brain");
        hspKeywords.add("esophagus");
        hspKeywords.add("eyes");
        hspKeywords.add("gallbladder");
        hspKeywords.add("heart");
        hspKeywords.add("intestines");
        hspKeywords.add("kidney");
        hspKeywords.add("liver");
        hspKeywords.add("lung");
        hspKeywords.add("ovaries");
        hspKeywords.add("pancreas");
        hspKeywords.add("parathyroids");
        hspKeywords.add("pituitary");
        hspKeywords.add("prostate");
        hspKeywords.add("spleen");
        hspKeywords.add("stomach");
        hspKeywords.add("testicles");
        hspKeywords.add("thymus");
        hspKeywords.add("thyroid");
        hspKeywords.add("uterus");
        hspKeywords.add("veins");
        hspKeywords.add("neurologist");
        hspKeywords.add("physician");
        hspKeywords.add("neurosurgeon");
        hspKeywords.add("plastic surgeon");
        hspKeywords.add("general surgeon");
        hspKeywords.add("ophthalmologist");
        hspKeywords.add("cancer");
        hspKeywords.add("cardiologist");
        hspKeywords.add("orthopedics");
        hspKeywords.add("neurologist");
        hspKeywords.add("dentist");
        hspKeywords.add("orthodontist");
        hspKeywords.add("paediatricians");
        hspKeywords.add("psychiatrist");
        hspKeywords.add("urologist");
        hspKeywords.add("nephrologist");
        hspKeywords.add("gynacologist");
        hspKeywords.add("severe headache");
        hspKeywords.add("unconsciousness");
        hspKeywords.add("giddiness");
        hspKeywords.add("blackout");
        hspKeywords.add("convulsion");
        hspKeywords.add("paralysis");
        hspKeywords.add("acute confusion");
        hspKeywords.add("swelling head");
        hspKeywords.add("swelling face");
        hspKeywords.add("swelling neck");
        hspKeywords.add("blindness");
        hspKeywords.add("any eye problem");
        hspKeywords.add("loss of vision");
        hspKeywords.add("bleeding from ear");
        hspKeywords.add("bleeding from nose");
        hspKeywords.add("difficulty in swallowing");
        hspKeywords.add("stuck fish bone in throat");
        hspKeywords.add("stuck bone in throat");
        hspKeywords.add("any nose problem");
        hspKeywords.add("any ear problem");
        hspKeywords.add("bleeding from mouth");
        hspKeywords.add("accidentally swallowed object/coin");
        hspKeywords.add("vomiting");
        hspKeywords.add("swelling in mouth");
        hspKeywords.add("wound/patch in mouth");
        hspKeywords.add("unable to swallow");
        hspKeywords.add("chest pain");
        hspKeywords.add("palpitation");
        hspKeywords.add("fast heart beat");
        hspKeywords.add("slow heart beat");
        hspKeywords.add("missed heart beat");
        hspKeywords.add("swelling");
        hspKeywords.add("breathlessness");
        hspKeywords.add("asthma");
        hspKeywords.add("severe cough");
        hspKeywords.add("blood in cough");
        hspKeywords.add("pain in abdomen");
        hspKeywords.add("blood in vomitus");
        hspKeywords.add("bleeding per rectum");
        hspKeywords.add("absolute constipation");
        hspKeywords.add("abdominal swelling");
        hspKeywords.add("unable to swallow");
        hspKeywords.add("anus any problem");
        hspKeywords.add("diarrhea");
        hspKeywords.add("vomiting");
        hspKeywords.add("indigestion");
        hspKeywords.add("abdomen hernia");
        hspKeywords.add("groin hernia");
        hspKeywords.add("pain");
        hspKeywords.add("swelling");
        hspKeywords.add("bedsore");
        hspKeywords.add("swelling");
        hspKeywords.add("discoloration");
        hspKeywords.add("wound");
        hspKeywords.add("pain");
        hspKeywords.add("weakness");
        hspKeywords.add("fracture");
        hspKeywords.add("toothache");
        hspKeywords.add("gum bleeding");
        hspKeywords.add("any dental problem");
        hspKeywords.add("tooth deformity");
        hspKeywords.add("gum swelling");
        hspKeywords.add("ulcer in mouth");
        hspKeywords.add("all problems");
        hspKeywords.add("fever");
        hspKeywords.add("skin eruptions");
        hspKeywords.add("rashes");
        hspKeywords.add("suicidal tendencies");
        hspKeywords.add("acute mania");
        hspKeywords.add("excessive sweating");
        hspKeywords.add("excessive weakness");
        hspKeywords.add("insomnia (inability to sleep)");
        hspKeywords.add("abnormal body sensation");
        hspKeywords.add("abnormal body movement");
        hspKeywords.add("wound anywhere");
        hspKeywords.add("jaundice");
        hspKeywords.add("breast surgeon");
        hspKeywords.add("gastroenetrologist");
        hspKeywords.add("dr.");
        hspKeywords.add("doctor");
        hspKeywords.add("blood bank");
        hspKeywords.add("ambulance");
        hspKeywords.add("eye bank");
        hspKeywords.add("patient");
        hspKeywords.add("drug");
        hspKeywords.add("chemist");
        hspKeywords.add("wellness");
        hspKeywords.add("hearing aid");
        hspKeywords.add("physio");
        hspKeywords.add("physiotherapy");
        hspKeywords.add("physiotherapist");
        hspKeywords.add("janaushadi");
        hspKeywords.add("Medi");
        hspKeywords.add("Aushad");
        hspKeywords.add("Aushadi");
        hspKeywords.add("Infertility");
        hspKeywords.add("pharma");
        hspKeywords.add("vivante");
        hspKeywords.add("Lenskart");
        hspKeywords.add("Dog");
        hspKeywords.add("Cat");
        hspKeywords.add("Pet");
        hspKeywords.add("Veterinary");
        hspKeywords.add("Animal");
        hspKeywords.add("Vet");
        hspKeywords.add("Happy tails");
        hspKeywords.add("Pets");
        hspKeywords.add("Optics");
        hspKeywords.add("Opticals");
        hspKeywords.add("Ayurveda");
        hspKeywords.add("Ayurved");
        hspKeywords.add("Skin");
        hspKeywords.add("Netralaya");
        hspKeywords.add("Optician");
        hspKeywords.add("Eyewear");
        hspKeywords.add("Eye wear");
        hspKeywords.add("Eye Plus");
        hspKeywords.add("Imaging centre");
        hspKeywords.add("eye ");
        hspKeywords.add("dr ");
        hspKeywords.add("dental");
        hspKeywords.add("ortho ");

        return hspKeywords;
    }
}
